### ISSUE TITLE
Duplicate times occasionally 

### ISSUE THREAD

**Issue by craigmate** [bremor/public_transport_victoria#12]
HI Brendon

Just a quick one which I have noticed.  Occasionally I notice that the next train to depart and the one after that are displayed with the same time

See example

![image](https://user-images.githubusercontent.com/51873021/103451056-3abb4180-4d13-11eb-8a97-ec796293e47d.png)

It however it not all the time and sometimes it seems to display the correct times. 

Either way, only a minor issue, and thanks again for this awesome custom component (As well as the bureau_of_meteorology
 one as well)

**Comment by bremor** [comment]
Thanks Craig, I know what is going on here because I encountered the same issue on one of my other custom components.
I need to add something called an UpdateCoordinator which changes the way sensors are updated, I will do it when I get a chance 👍

**Comment by catatonicChimp** [comment]
Just throwing this in here for reference.
Going to add this on the top of my list to do as i currently have some very hacky ways of updating the feed to stay in sync
https://developers.home-assistant.io/docs/integration_fetching_data/
https://developers.home-assistant.io/blog/2024/08/05/coordinator_async_setup/

**Comment by catatonicChimp** [comment]
updated the sensor to use DataUpdateCoordinator so should keep things in Sync  https://github.com/bremor/public_transport_victoria/commit/29cdbb8be6680dc528054d1fa90206b2f979ab9d
