### ISSUE TITLE
Addition of RideSpace crowding information

### ISSUE THREAD

**Issue by teleksterling** [bremor/public_transport_victoria#13]
PTV/TransportX has launched [RideSpace](https://ridespace.coronavirus.vic.gov.au/), which reports a realtime estimate of crowding on platforms and PT services. 

I don't know whether there is API access to the data or not.

On its launch DOT reported that "We’ll continue to monitor RideSpace and its usage over the next few months, as well as investigating options to expand it to include tram, regional train and bus capacity; and integration into our other products (like the PTV app) and third-party services (like Google Maps)." which would suggest that they don't have an API yet. 

So I guess just consider this issue a bookmark to come back to it when they do?

**Comment by bremor** [comment]
Thanks for the heads up. PTV send an email to anyone with an API key when there is any change to the API so we will be the first to find out.
