### ISSUE TITLE
Relative not absolute times

### ISSUE THREAD

**Issue by olleepalmer** [bremor/public_transport_victoria#15]
Is it possible to modify the times so that you can see X minutes until departure?

e.g. If departure time is the same as current time, print "Now"
If departure time is 5 minutes from current time, print "5 minutes"

**Comment by catatonicChimp** [comment]
Unfortunately this isn't a value we get from the API, but you can easily do a template  in Home assistant 

e.g. 

```
{% set estimated_departure =
as_timestamp(state_attr('sensor.upfield_line_to_city_flinders_street_from_coburg_station_0',
'estimated_departure_utc')) %}

{% set minutes_until_departure = ((estimated_departure -
as_timestamp(now())) // 60) | int %}
    
{{minutes_until_departure}}
```
