### ISSUE TITLE
Unable to create integration for Train

### ISSUE THREAD

**Issue by auSchizm** [bremor/public_transport_victoria#18]
![image](https://user-images.githubusercontent.com/52204304/164701307-e1487fab-d98d-4840-b170-9af0a46ee699.png)

Unable to set up integration for Train. Says malformed dictionary value. Other modes can be added, so I know the API key is correct.

**Comment by raganzone** [comment]
I'm also getting the same error for _Train_ option. It is working fine for _Tram_, _Bus_ and _V-Line_. For _Night Bus_ option I'm getting "Unknown error".

**Comment by ghost** [comment]
Same for me, unable to select a Train. Bus works fine.

**Comment by bozboz1** [comment]
Same issue at my end as well.

**Comment by t0mmy44-h** [comment]
Same here

EDIT:

I've found a workaround, you need to cast the user input for this step to an `int`. See this snippet:
https://github.com/bremor/public_transport_victoria/blob/9ab45a1cd65a47d391e44b41819d8288e09d0fab/custom_components/public_transport_victoria/config_flow.py#L67-L71

Change each instance of
```python
user_input[CONF_ROUTE_TYPE]
```
to
```python
int(user_input[CONF_ROUTE_TYPE])
```

@bremor I'm not sure if this is really what you should be doing here, but I think what's happening is that `0` is coming back from the form to the python process as a string, which breaks the dictionary index. I'm not really a python dev (ruby & scala), but this works if anyone wants to give it a try.

**Comment by loryanstrant** [comment]
I've got the same problem as well.
@t0mmy44-h have you thought of doing a pull request on your modification?
That would make it easier for @bremor to publish if they're happy with it.

**Comment by michaelblight** [comment]
I fixed it by changing lines 64-73 to:
```
        if user_input is not None:
            try:
                route_type = int(user_input[CONF_ROUTE_TYPE])
                self.routes = await self.connector.async_routes(
                    route_type
                )

                self.data[CONF_ROUTE_TYPE] = route_type
                self.data[CONF_ROUTE_TYPE_NAME] = self.route_types[route_type]

                return await self.async_step_routes()
```
However, I also had to change line 60 to pass 0 as an integer rather than a string:
```
            vol.Required(CONF_ROUTE_TYPE, default=0): vol.In(self.route_types),
```
I will do a PR tomorrow.

**Comment by michaelblight** [comment]
PR created. I found that I only needed to change the default to an integer to get it to work. My fork is [here](https://github.com/michaelblight/public_transport_victoria) if anybody wants to try it.

**Comment by loryanstrant** [comment]
Brilliant, thanks so much @michaelblight, I've applied that fix successfully and added the train functionality in.

**Comment by auSchizm** [comment]
Fantastic, thanks @michaelblight and @bremor. Latest update has fixed it. Working great now.
