### ISSUE TITLE
Entity does not always update with homeassistant.update_entity

### ISSUE THREAD

**Issue by derekjwhitten** [bremor/public_transport_victoria#21]
Hello,

Firstly, loving this integration. I'm using it to send voice alerts over my Google Home speakers for upcoming trains at important times of the day, and have an entities card on one of my dashboards which shows the next 5 trains.

The other day I had trouble getting the next train time to update.  I called the homeassistant.update_entity service but it was stuck with a 12 minute old update.  I was out and about so couldn't get any logs, but do have this screenshot showing stop ID, rout ID etc which is hopefully helpful.

If it happens again I'll try and capture more details, but wanted to log there here in case there is a problem somewhere in the integration.

![image](https://github.com/bremor/public_transport_victoria/assets/5736382/1a9d96b7-5434-4114-ae19-4871460201e0)

**Comment by evergreen0057** [comment]
I've also noticed this issue. Triggering an update never seems to update the entity anymore 

Even the recommended automation that refreshes the times during peak hour no longer seems to work

**Comment by TwoBigPaws** [comment]
Yes, I am also having trouble with the updater automation.  I am getting this error:
"Message malformed: required key not provided @ data['trigger'][0]['platform']"

**Comment by catatonicChimp** [comment]
I've updated the sensor to use DataUpdateCoordinator instead, so this should be fixed in the next release, still has a 10min update on new data, note that unless there is new data coming in, you won't see the "time since last update" tag, next to the entity, update its value

**Comment by derekjwhitten** [comment]
Awesome, thanks @catatonicChimp !
