### ISSUE TITLE
PTV not responding when I request a API key

### ISSUE THREAD

**Issue by jralph23** [bremor/public_transport_victoria#22]
I followed the instructions and emailed the correct email address at PTV to get the auth key, etc. but I am not getting any response. It's been nearly 2 weeks. Anyone else know what to do here?

**Comment by james-callahan** [comment]
They took a bit of a week to reply to me.

**Comment by jralph23** [comment]
I got it. It only took about 4 weeks. Now my HA is smashing it with requests every minute. :)

**Comment by catatonicChimp** [comment]
Yip it took a few weeks for them to reply with the API details.
Closing Issue..
